service: aws-node-http-api-project
frameworkVersion: "3"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource:
        { "Fn::Join": ["", ["arn:aws:s3:::test-bucket-leap2022", "/*"]] }

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  api:
    handler: handler.api
    events:
      - httpApi:
          path: /{routeName}
          method: "*"
  upload:
    handler: handler.getPresignedUrl
    events:
      - httpApi:
          path: /getPresignedUrl
          method: "GET"

resources:
  Resources:
    DemoBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: test-bucket-leap2022
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
